#!/usr/bin/env perl

use strict;
use warnings;
use lib $ENV{C_TAP_SOURCE} . "/tests-lib/perl5";
use afstest qw(src_path obj_path);
use Test::More;

sub completion_helper {
    my $output;

    my $cmd_wrapper = obj_path("tests/cmdwrap");
    my $comptest = obj_path("tests/cmd/comptest");
    my @args = ($cmd_wrapper, $comptest, '-completion-helper', '--');
    push(@args, @_);

    open(my $pipe, "-|", @args) or BAIL_OUT("Unable to run '@args': $!");
    $output = do { local $/; <$pipe> };
    chomp $output;
    $output =~ s/\s+$//; # remove trailing whitespaces
    if (!close($pipe)) {
        if ($!) {
            BAIL_OUT("Failed to close pipe: $!");
        }
        my $exit_code = $? >> 8;
        my $signal = $? & 127;

        if ($signal) {
            my $coredump = ($? & 128) ? " (core dumped)" : "";
            BAIL_OUT("'@args' died with signal $signal$coredump");
        }
        BAIL_OUT("Command '@args' failed with exit code ${exit_code} (status $?)");
    }
    return $output;
}

my @test_cases = (
    {
        name => 'top-level completions',
        args => ['1', 'comptest', ''],
        expected => 'apropos five four help one three two version',
    },
    {
        name => 'options for "one" command',
        args => ['2', 'comptest', 'one', '-'],
        expected => '-apple -banana -peach -pear -plum -help',
    },
    {
        name => 'options for "duo" command alias',
        args => ['2', 'comptest', 'duo', '-'],
        expected => '-apple -banana -peach -orange -lime -help',
    },
    {
        name => 'do not repeat -help option',
        args => ['3', 'comptest', 'one', '-help', '-'],
        expected => '-apple -banana -peach -pear -plum',
    },
    {
        name => 'no options for CMD_SINGLE value position',
        args => ['3', 'comptest', 'one', '-banana', '-'],
        expected => '',
    },
    {
        name => 'no options for CMD_LIST value position',
        args => ['3', 'comptest', 'one', '-peach', '-'],
        expected => '',
    },
    {
        name => 'zero pos_cword has no completions',
        args => ['0', 'comptest', 'one', '-'],
        expected => '',
    },
    {
        name => 'negative pos_cword has no completions',
        args => ['-1', 'comptest', 'one', '-'],
        expected => '',
    },
    {
        name => 'out of range pos_cword has no completions',
        args => ['3', 'comptest', 'one', '-'],
        expected => '',
    },
    {
        name => 'unknown command has no completions',
        args => ['2', 'comptest', 'unknown', '-'],
        expected => '',
    },
    {
        name => 'do not repeat CMD_SINGLE option',
        args => ['4', 'comptest', 'one', '-banana', 'value1', '-'],
        expected => '-apple -peach -pear -plum -help',
    },
    {
        name => 'do not repeat multiple CMD_SINGLE options',
        args => ['6', 'comptest', 'one', '-plum', 'value1', '-banana', 'value2', '-'],
        expected => '-apple -peach -pear -help',
    },
    {
        name => 'do not repeat CMD_FLAG option',
        args => ['3', 'comptest', 'one', '-apple', '-'],
        expected => '-banana -peach -pear -plum -help',
    },
    {
        name => 'allow repeated CMD_LIST option',
        args => ['4', 'comptest', 'one', '-peach', 'value1', '-'],
        expected => '-apple -banana -peach -pear -plum -help',
    },
    {
        name => 'CMD_LIST repeated multiple times',
        args => ['6', 'comptest', 'one', '-peach', 'value1', '-peach', 'value2', '-'],
        expected => '-apple -banana -peach -pear -plum -help',
    },
    {
        name => 'all single options used',
        args => ['8', 'comptest', 'one', '-banana', 'val1', '-plum', 'v2', '-apple', '-pear', '-'],
        expected => '-peach -help',
    },
    {
        name => 'empty subcommand',
        args => ['2', 'comptest', '', '-'],
        expected => '',
    },
    {
        name => 'whitespace subcommand',
        args => ['2', 'comptest', ' ', '-'],
        expected => '',
    },
    {
        name => 'non-numeric pos_cword',
        args => ['abc', 'comptest', 'one', '-'],
        expected => '',
    },

    # TODO: Many, many more tests. Be sure to check "edge cases".
);

plan tests => scalar @test_cases;

foreach my $test (@test_cases) {
    my $got = completion_helper(@{$test->{args}});
    is($got, $test->{expected}, $test->{name});
}
